name: Run Tests

on:
  push
  
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: ruby/setup-ruby-pkgs@v1
      with:
        ruby-version: 3.0 
    
    - name: run unit tests
      run: |
        gem install bundler
        cd /home/runner/work/dataverse-helper/dataverse-helper
        ls
