name: Run Tests

on:
  push
  
permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']

    steps:
    - name: Install bundle
      run: gem install bundler
      
    - name: Install gems
      run: bundle install -j10
      
    - name: Run tests
      run: bundle exec rspec
